# /etc/systemd/system/carracho.service.d/webadmin.conf
#
# Es gibt keinen separaten carracho-webadmin.service.
# carracho-server startet und beendet den WebAdmin selbst.
[Service]
EnvironmentFile=/opt/carracho/etc/carracho-server.env
